### ISSUE TITLE
Failed to complete OAuth handshake with LinkedIn

### ISSUE THREAD

**Issue by gfb107** [PoBuchi/pauli-linkedin-oauth#2]
Getting this exception:

> Exception while invoking method 'login' Error: Failed to complete OAuth handshake with LinkedIn. Cannot read property 'post' of undefined
> I20180131-08:47:28.500(-5)?     at getTokenResponse (packages/pauli:linkedin-oauth/linkedin-server.js:87:11)

The problem is you're using
`Meteor.http.post(...)`
rather than
`HTTP.post(...)`

There are other places where you use Meteor.http.post and Meteor.http.get

I got past this by placing this hack is my server-side code:
`if ( !Meteor.http ) {
  Meteor.http = HTTP;
}`

**Comment by PoBuchi** [comment]
will update tomorrow
