### ISSUE TITLE
V2 upgrade

### ISSUE THREAD

**Issue by juho** [PoBuchi/pauli-linkedin-oauth#4]
Hey hey,

Do you have plans to update this for Linkedin API V2 so that it will work past March 1st 2019?

**Comment by PoBuchi** [comment]
@juho, yes will be dealing with this on this weekend

**Comment by PoBuchi** [comment]
@juho [done](https://github.com/PoBuchi/pauli-linkedin-oauth/commit/a4b72578286a4c7c47cb26d433421148fa0897b9)

**Comment by juho** [comment]
Thanks!
